apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-main-set
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/andres20980/gitops-poc.git
        revision: main
        directories:
          - path: apps/*  # Este patr칩n busca todas las aplicaciones en ./apps/X
  template:
    metadata:
      name: 'app-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/andres20980/gitops-poc.git
        targetRevision: main
        path: '{{path}}/services'  # Ahora apuntamos a /services dentro de cada aplicaci칩n
        helm:
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'  # El namespace ser치 el nombre de la aplicaci칩n
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
