apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-gitops
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/andres20980/gitops-poc.git
              revision: main
              directories:
                - path: apps/*
          - list:
              elements:
                - env: dev
                - env: pre
  template:
    metadata:
      name: '{{path.basename}}-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/andres20980/gitops-poc.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
            - common-values.yaml
            - values-{{env}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
