apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-main-set
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/andres20980/gitops-poc.git
        revision: main
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/andres20980/gitops-poc.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
