apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: shared-services-set
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/andres20980/gitops-poc.git
        revision: main
        directories:
          - path: shared-services/*
  template:
    metadata:
      name: '{{path.basename}}-shared'
    spec:
      project: default
      source:
        repoURL: oci://ghcr.io/andres20980
        chart: chart-base             # Chart fijo
        targetRevision: 1.2.1         # Versión del chart-base en OCI
        helm:
          valueFiles:
            - values.yaml
            - common-values.yaml
            - values-dev.yaml       # o values-pre.yaml según el entorno
      destination:
        server: https://kubernetes.default.svc
        namespace: shared-services
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
