apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/andres20980/chart-base
    chart: chart-base
    targetRevision: 1.2.1
    helm:
      valueFiles:
        - argodeploy/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: test-helloworld
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
