chart-base:
  nameOverride: helloworld
  app:
    registry: ghcr.io/andres20980
    image: helloworld-app
    version: local-v1
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
  carbone:
    enabled: false
