# kustomize/components/world/base/kustomization.yaml v2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: msw-cic-helm-chart-base
  releaseName: world
  version: 1.0.0
  repo: ../../../helm-base
  valuesFile: values.yaml