# kustomize/components/world/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrelease.yaml

configMapGenerator:
  - name: world-values
    files:
      - values.yaml

patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: world
    patch: |-
      - op: replace
        path: /spec/chart/spec/chart
        value: ./helm-base
      - op: replace
        path: /spec/chart/spec/sourceRef/kind
        value: GitRepository
      - op: replace
        path: /spec/chart/spec/sourceRef/name
        value: gitops-poc-repo # Replace with your actual Flux GitRepository name if different
      - op: replace
        path: /spec/valuesFrom/0/sourceRef/name
        value: world-values
