# base/helloworld-chart/templates/service.yaml v1.0.0
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: helloworld
