# components/helloworld/deployment.yaml v1.0.0
# Defines the deployment for the helloworld application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: helloworld
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: nginxdemos/hello:plain-text # A simple image that responds to HTTP requests.
        ports:
        - containerPort: 80
