chart-base:
  nameOverride: helloworld

  affinity: {}
  nodeSelector: {}
  tolerations: []

  app:
    registry: ghcr.io/andres20980
    image: helloworld-app
    version: local-v1
    env:
      - name: CARBONE_URL
        value: http://shcomp-carbone.shared-services.svc.cluster.local:8080

  replicaCount: 1

  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000

  carbone:
    enabled: true
