# argo-cd/apps-of-apps/app-world-dev.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: world-dev
  namespace: argocd
spec:
  project: default
  source:
    # This now points directly to the Helm Umbrella chart
    repoURL: https://github.com/andres20980/gitops-poc.git # ⚠️ VERIFY THIS URL
    targetRevision: HEAD
    path: apps/world
    helm:
      # Here you could specify a different values file for each environment
      # For now, we use the default values.yaml
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: world-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
