# kustomize/apps/kustomiworld/overlays/pre/kustomization.yaml v1.0.0
# Kustomization overlay for the kustomiworld PRE environment.
# This file customizes the base application for the pre-production environment.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inherit from the base configuration.
bases:
  - ../../base

# Set the namespace for all resources in this overlay.
namespace: kustomiworld-pre

# Patches are used to modify specific fields in the base resources.
# Here, we are changing the replica count for each deployment.
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: helloworld
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: byebyeworld
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: moon