# github-image-pull-secret.yaml v1.0.0
apiVersion: v1
kind: Secret
metadata:
  name: github-image-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaXRodWIuY29tIjogewogICAgICAiYXV0aCI6ICJaMmh3WDNBNU5tUTVNME4zUVZOSFNFeHBjVWhYZGtWb01uSnlTMWx6VEVkSWVUSXhXRXhsVnc9PSIKICAgIH0KICB9Cn0=