apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pdf-processor-app
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: carbone-shcomp  # Esta es la referencia al componente ya existente
            namespace: shared-services  # Aquí está el namespace donde el componente ya está desplegado
  template:
    metadata:
      name: 'pdf-processor-app'  # Nombre de la app que consume el componente 'carbone-shcomp'
    spec:
      project: default
      source:
        repoURL: https://github.com/andres20980/gitops-poc.git
        targetRevision: main
        path: apps/pdf-processor  # Ruta de la app pdf-processor
        helm:
          valueFiles:
            - values.yaml
            - common-values.yaml
            - values-dev.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: pdf-processor-dev  # El namespace de 'pdf-processor'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
