apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pdf-processor-app
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: carbone-shcomp  # El nombre del componente existente
            namespace: shared-services  # El namespace donde 'carbone-shcomp' ya está desplegado
  template:
    metadata:
      name: 'pdf-processor-app'  # El nombre de la app agregadora (pdf-processor)
    spec:
      project: default
      source:
        repoURL: https://github.com/andres20980/gitops-poc.git
        targetRevision: main
        path: apps/pdf-processor  # El path de la app de agregador en Git (aunque no tiene charts ni values)
        helm:
          valueFiles:
            - values.yaml
            - common-values.yaml
            - values-dev.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: pdf-processor-dev  # El namespace donde se desplegará 'pdf-processor'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
