apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pdf-processor-app
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: carbone-shared  # Hacemos referencia al servicio compartido
            path: shared-services/carbone
            namespace: shared-services
  template:
    metadata:
      name: '{{name}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/andres20980/gitops-poc.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
            - common-values.yaml
            - values-dev.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
