# kustomize/apps/world/overlays/dev/kustomization.yaml v1.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inherit all resources from the base application definition.
resources:
  - ../../base

# Specify the target namespace for the 'dev' environment.
namespace: world-dev
