# kustomize/apps/world/overlays/dev/kustomization.yaml v2.0.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

namespace: world-dev

images:
  - name: ghcr.io/andres20980/helloworld-app
    newTag: 25f6004
patches:
- patch: |-
    - op: add
      path: /spec/template/metadata/labels/rollout-timestamp
      value: "2025-07-03-10-46-00Z"
  target:
    kind: Rollout
    name: moon