# argo-cd/projects/project-dev.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-project
  namespace: argocd
spec:
  description: Development Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: space-dev
    server: https://kubernetes.default.svc
  - namespace: world-dev
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
