# argo-cd/projects/project-pre.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pre-project
  namespace: argocd
spec:
  description: Pre-production Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: space-pre
    server: https://kubernetes.default.svc
  - namespace: world-pre
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
