apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: comp-carbone-world
  namespace: argocd  # El namespace donde se crea la aplicación en ArgoCD
spec:
  project: default
  source:
    repoURL: https://github.com/andres20980/gitops-poc.git  # Repositorio Git donde está tu código
    targetRevision: HEAD  # Se utiliza la rama principal
    path: shared-services/carbone  # Ruta al gráfico Helm de la aplicación 'carbone'
    helm:
      valuesFiles:
        - values.yaml         # Valores predeterminados de la aplicación
        - common-values.yaml  # Valores comunes que se aplican a todos los entornos
        - values-dev.yaml     # Valores específicos para el entorno de desarrollo
  destination:
    server: https://kubernetes.default.svc
    namespace: carbone  # Namespace donde se desplegará la aplicación 'carbone'
  syncPolicy:
    automated:
      prune: true  # Eliminar recursos que ya no son necesarios
      selfHeal: true  # Reparar recursos que están fuera de sincronización
    syncOptions:
      - CreateNamespace=true  # Crear automáticamente el namespace si no existe
