# kustomize/apps/world/base/kustomization.yaml v2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../components/helloworld/base
- ../../../components/moon/base
- ../../../components/carbone/base

namePrefix: world-

labels:
- includeSelectors: true
  pairs:
    app: world-app