# components/helloworld-chart/kustomization.yaml v1.0.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: helloworld-chart
  releaseName: helloworld
  version: 0.1.0
