# kustomize/apps/world/overlays/pre/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: # Changed from 'bases' to 'resources' for future compatibility
  - ../../base

namespace: world-pre

patches:
  - target:
      kind: HelmRelease
      name: world-helloworld
    patch: |-
      - op: replace
        path: /spec/values/ingress/enabled
        value: true
      - op: replace
        path: /spec/values/ingress/host
        value: helloworld-pre.world.example.com
