# kustomize/components/moon/base/rollout.yaml v1.0.0
# Argo Rollout definition for the moon component using a Blue-Green strategy.
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: moon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moon
  template:
    metadata:
      labels:
        app: moon
    spec:
      containers:
        - name: moon
          image: "nginxdemos/hello:plain-text"
          ports:
            - containerPort: 80
  # This section defines the Blue-Green deployment strategy for the moon component.
  strategy:
    blueGreen: 
      activeService: moon-service
      previewService: moon-service-preview
      autoPromotionEnabled: false