# kustomize/components/moon/base/service.yaml v1.0.0
# Base service for the moon component.
apiVersion: v1
kind: Service
metadata:
  name: moon-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: moon