# kustomize/components/moon/base/values.yaml
serviceName: moon
image: your-repo/moon-service:latest # Placeholder for moon image
replicas: 1
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
