# argocd/apps/dev/app-world-dev.yaml v2.0.0
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: world-dev
  namespace: argocd
spec:
  project: applications-dev # Assign to the dev project
  source:
    repoURL: https://github.com/andres20980/gitops-poc.git
    targetRevision: HEAD
    path: kustomize/apps/world/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: world-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true