# argo-cd/apps/dev/app-world-dev.yaml v1.0
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-world-dev
  namespace: argocd
spec:
  project: dev-project
  source:
    repoURL: https://github.com/andres20980/gitops-poc.git # Replace with your repo URL
    targetRevision: HEAD
    # Path to the Kustomize overlay for this application and environment.
    path: kustomize/apps/world/overlays/dev
    # No plugin is needed, Argo CD will detect kustomization.yaml automatically.
  destination:
    server: https://kubernetes.default.svc
    namespace: world-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
