# kustomize/components/sun/base/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sun
spec:
  interval: 1m
  chart:
    spec:
      chart: placeholder
      sourceRef:
        kind: GitRepository
        name: placeholder
  valuesFrom:
    - kind: ConfigMap
      name: placeholder
