# kustomize/components/sun/base/kustomization.yaml v1.2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Using 'name' for the local Helm chart path and updated labels syntax.
helmCharts:
  - name: ../../../../helm-base
    releaseName: sun
    valuesFile: values.yaml

# Updated 'commonLabels' to the new 'labels' syntax.
labels:
- pairs:
    app.kubernetes.io/component: sun
  includeSelectors: true
