# kustomize/components/sun/base/kustomization.yaml v1.4
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: charts/helm-base # Updated to root-relative path
    releaseName: sun
    valuesFile: values.yaml

labels:
- pairs:
    app.kubernetes.io/component: sun
  includeSelectors: true