# kustomize/components/sun/base/kustomization.yaml v2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: ../../../helm-base
  releaseName: sun
  version: 1.0.0
  valuesFile: values.yaml