# kustomize/components/sun/base/values.yaml
serviceName: sun
image: your-repo/sun-service:latest # Placeholder for sun image
replicas: 1
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
