# argo-cd/apps/pre/app-space-pre.yaml v2.0
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-space-pre
  namespace: argocd
spec:
  project: pre-project
  source:
    repoURL: https://github.com/andres20980/gitops-poc.git # Replace with your repository URL
    targetRevision: HEAD
    path: kustomize/apps/space/overlays/pre
    helm:
      values: |
        world:
          ingress:
            enabled: true
            host: world-pre.space.example.com
  destination:
    server: https://kubernetes.default.svc
    namespace: space-pre
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true