# argocd/apps/pre/app-space-pre.yaml v2.0.0
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: space-pre
  namespace: argocd
spec:
  project: applications-pre # Assign to the pre project
  source:
    repoURL: https://github.com/andres20980/gitops-poc.git
    targetRevision: HEAD
    path: kustomize/apps/space/overlays/pre
  destination:
    server: https://kubernetes.default.svc
    namespace: space-pre
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true