# argo-cd/apps/pre/app-space-pre.yaml v1.0
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-space-pre
  namespace: argocd
spec:
  project: pre-project
  source:
    repoURL: https://github.com/andres20980/gitops-poc.git # Replace with your repo URL
    targetRevision: HEAD
    # Path to the Kustomize overlay for this application and environment.
    path: kustomize/apps/space/overlays/pre
  destination:
    server: https://kubernetes.default.svc
    namespace: space-pre
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
