# argo-cd/apps/app-world-dev.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: world-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andres20980/gitops-poc.git # ⚠️ VERIFY THIS URL
    targetRevision: HEAD
    path: apps/world
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: world-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
