# argo-cd/apps/app-space-pre.yaml v1.0.0
# Argo CD Application definition for the 'space' application in the PRE environment.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: space-pre
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andres20980/gitops-poc.git
    targetRevision: HEAD
    path: kustomize/apps/space/overlays/pre
  destination:
    server: https://kubernetes.default.svc
    namespace: space-pre
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true