# kustomize/apps/kustomispace/base/kustomization.yaml v1.0.0
# Base Kustomization for the kustomispace application.
# This file aggregates the bases of the sun and moon components.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../components/sun/base
  - ../../../components/moon/base