# environments/pro/patch-replicas-and-env.yaml v1.0.0
# Patch for PRO: 5 replicas and add an environment variable
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: helloworld
          env:
            - name: "ENVIRONMENT"
              value: "production"
