# Valores base para carbone (puedes poner aquí los valores comunes a todos los entornos)
chart-base:
  nameOverride: carbone
  app:
    registry: ghcr.io/andres20980
    image: carbone
    version: local-v1
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  env:
    LOG_LEVEL: INFO
