# kustomize/components/helloworld/base/kustomization.yaml v1.9
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Using an absolute path for debugging purposes to confirm the root cause.
helmCharts:
  - name: ../../../charts/helm-base
    releaseName: helloworld
    valuesFile: values.yaml

labels:
- pairs:
    app.kubernetes.io/component: helloworld
  includeSelectors: true
