# kustomize/components/helloworld/base/rollout.yaml v1.1.0
# Argo Rollout definition for the helloworld component.
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: "nginxdemos/hello:plain-text"
          ports:
            - containerPort: 80
  strategy:
    canary:
      # These fields connect the rollout to the services.
      stableService: helloworld-service
      canaryService: helloworld-service-canary
      steps:
      - setWeight: 20
      - pause: {}