# kustomize/components/helloworld/base/service.yaml v1.1.0
# This is the STABLE service.
# Argo Rollouts will manage the selectors of this service to shift traffic
# between the stable and canary versions.
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: helloworld