apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: world-app
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: helloworld
            path: components/helloworld
            namespace: world-dev
          - name: carbone-shared  # Referencia a shared service carbone
            path: shared-services/carbone
            namespace: shared-services  # Namespace donde está el shared service
  template:
    metadata:
      name: '{{name}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/andres20980/gitops-poc.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
            - common-values.yaml
            - values-dev.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
