chart-base:
  nameOverride: carbone
  affinity: {}
  nodeSelector: {}
  tolerations: []
  app:
    registry: ghcr.io/andres20980
    image: carbone
    version: local-v1
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
  carbone:
    enabled: false
