# kustomize/apps/space/base/kustomization.yaml v1.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List of components that form the 'space' application.
resources:
  - ../../../components/sun
  - ../../../components/moon
  - ../../../components/carbone

# Apply a common label to identify all resources as part of this application.
commonLabels:
  app.kubernetes.io/part-of: space-app
