# kustomize/apps/space/base/kustomization.yaml v1.2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../components/sun/base
  - ../../../components/moon/base
  - ../../../components/carbone/base

# Updated 'commonLabels' to the new 'labels' syntax to remove warnings.
labels:
- pairs:
    app.kubernetes.io/part-of: space-app
  includeSelectors: true
