# kustomize/apps/kustomispace/base/kustomization.yaml v1.2.0
# Added the third-party carbone component to the application.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../components/custom/sun/base
  - ../../../components/custom/moon/base
  - ../../../components/third-party/carbone/base
