# kustomize/apps/space/base/kustomization.yaml v2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../components/world/base
- ../../../components/sun/base
- ../../../components/moon/base
- ../../../components/carbone/base

namePrefix: space-

labels:
- includeSelectors: true
  pairs:
    app: space-app