# kustomize/components/byebyeworld/base/deployment.yaml v1.0.0
# Base deployment for the byebyeworld component.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: byebyeworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: byebyeworld
  template:
    metadata:
      labels:
        app: byebyeworld
    spec:
      containers:
        - name: byebyeworld
          image: "nginxdemos/hello:plain-text"
          ports:
            - containerPort: 80