# kustomize/apps/kustomiworld/overlays/dev/kustomization.yaml v1.2.0
# Kustomization overlay for the kustomiworld DEV environment.
# This file customizes the base application for development.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inherit from the base configuration.

# Set the namespace for all resources in this overlay.
namespace: kustomiworld-dev

# We use a patch to add a timestamp label to the pod template.
# This change will trigger a new rollout without changing the container image.
patches:
- patch: |-
    - op: add
      path: /spec/template/metadata/labels/rollout-timestamp
      value: "2025-06-26T12-00-00Z"
  target:
    kind: Rollout
    name: helloworld
resources:
- ../../base
images:
- name: ghcr.io/andres20980/helloworld-app
  newName: ghcr.io/andres20980/helloworld-app
  newTag: 25f6004
