# apps/dev/app-helloworld-dev.yaml v1.0.0
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/andres20980/gitops-poc.git' # IMPORTANT: VERIFY YOUR REPO URL
    targetRevision: HEAD
    path: environments/dev # This app points to the DEV Kustomize overlay
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: helloworld-dev # Deploy to the dev namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
