# apps/app-of-apps.yaml v1.0.0
# This is the root application, also known as the "App of Apps".
# It manages all other applications in the specified path.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    # IMPORTANT: This URL is based on your previous input. Verify it is correct.
    repoURL: 'https://github.com/andres20980/gitops-poc.git'
    targetRevision: HEAD
    path: clusters/minikube # This points to the directory containing our cluster-specific app definitions.
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
