# clusters/minikube/helloworld-app.yaml v1.0.0
# Argo CD Application definition for the helloworld app on the minikube cluster.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld
  namespace: argocd # This application resource must live in the argocd namespace.
  finalizers:
    # The default behaviour is that when an Application CRD is deleted,
    # all of its child resources are also deleted.
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # IMPORTANT: This URL is based on your previous input. Verify it is correct.
    repoURL: 'https://github.com/andres20980/gitops-poc.git'
    targetRevision: HEAD
    path: components/helloworld # This points to the directory with the component manifests.
  destination:
    server: 'https://kubernetes.default.svc' # This means the local cluster where Argo CD is running.
    namespace: helloworld # The namespace where the app will be deployed.
  syncPolicy:
    automated:
      prune: true # Deletes resources that are no longer defined in Git.
      selfHeal: true # Reverts any manual changes made in the cluster to match Git.
    syncOptions:
      - CreateNamespace=true # Allows Argo CD to create the namespace if it doesn't exist.
