# kustomize/components/custom/helloworld/base/rollout.yaml v1.2.1
# Argo Rollout definition for the helloworld component.
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: "nginxdemos/hello:plain-text" # O la imagen de GHCR si ya la estás usando aquí
          ports:
            - containerPort: 80
      imagePullSecrets: # <-- Añade esta sección
      - name: github-image-pull-secret
  strategy:
    canary:
      stableService: helloworld-service
      canaryService: helloworld-service-canary
      steps:
      - setWeight: 20
      - pause: {}