# kustomize/components/custom/helloworld/base/rollout.yaml v2.1.0
# Updated to use the custom Python application from the correct GHCR path.
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          # Using the correct image path with your GitHub username
          image: "ghcr.io/andres20980/helloworld-app:v1"
          ports:
            # The new application runs on port 8080
            - containerPort: 8080
  strategy:
    canary:
      stableService: helloworld-service
      canaryService: helloworld-service-canary
      steps:
      - setWeight: 20
      - pause: {}