# kustomize/components/custom/helloworld/base/service.yaml v2.0.0
# Updated the targetPort to 8080 to match the new Python application.
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
    - port: 80
      # This now points to the port exposed by the Flask app in the container.
      targetPort: 8080
  selector:
    app: helloworld