# kustomize/components/custom/helloworld/base/values.yaml v1.1.0
# Default values for the helloworld component.
# Changed 'replicas' to 'replicaCount' for Helm standard consistency.

replicaCount: 1

name: helloworld

app:
  name: helloworld-app
  image:
    repository: ghcr.io/andres20980/helloworld-app
    tag: latest
  port: 8080
  message: "Hello World"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"