# Valores específicos para preproducción
chart-base:
  app:
    version: pre-build
  replicaCount: 2
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 150m
      memory: 192Mi
