# kustomize/components/custom/sun/base/kustomization.yaml v2.0.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
namespace: default
commonLabels:
  app: myapp
