# kustomize/apps/space/overlays/pre/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: # Changed from 'bases' to 'resources' for future compatibility
  - ../../base

namespace: space-pre

patches:
  - target:
      kind: HelmRelease
      name: space-world
    patch: |-
      - op: replace
        path: /spec/values/ingress/enabled
        value: true
      - op: replace
        path: /spec/values/ingress/host
        value: world-pre.space.example.com
