# helm-base/templates/rollout.yaml v1.0.0
# Template to generate an Argo Rollout resource when enabled in values.
{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1 # O puedes hacerlo configurable: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  # La plantilla del pod es casi idéntica a la de tu deployment.yaml
  # La copiamos de allí.
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config-map.yaml") . | sha256sum }}
    spec:
      # ... (aquí iría toda la sección spec.template.spec de tu deployment.yaml) ...
      containers:
      - name: app
        image: "{{ .Values.app.registry }}/{{ .Values.app.image }}:{{ .Values.app.version }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
      # ... etc ...

  # Esta es la parte clave: la estrategia se configura desde los values
  strategy:
    {{- if eq .Values.rollout.strategy "Canary" }}
    canary:
      stableService: {{ .Values.name }}-service
      canaryService: {{ .Values.name }}-service-canary
      steps:
      - setWeight: 20
      - pause: {}
    {{- else if eq .Values.rollout.strategy "BlueGreen" }}
    blueGreen: 
      activeService: {{ .Values.name }}-service
      previewService: {{ .Values.name }}-service-preview
      autoPromotionEnabled: false
    {{- end }}
{{- end }}