# helm-base/templates/service.yaml v1.0.0
# Template for the main Service resource.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    meta.helm.sh/release-name: {{ .Values.name }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.name }}