# helm-base/templates/service-canary.yaml v1.0.0
# Generates the canary service, only if the strategy is Canary.
{{- if and .Values.rollout.enabled (eq .Values.rollout.strategy "Canary") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service-canary
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.name }}
{{- end }}