# kustomize/components/carbone/base/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carbone # This name will be prefixed/suffixed by Kustomize higher up
spec:
  interval: 1m
  chart:
    spec:
      chart: placeholder # This will be patched
      sourceRef:
        kind: GitRepository
        name: placeholder # This will be patched
  valuesFrom:
    - kind: ConfigMap
      name: placeholder # This will be patched
