# kustomize/components/carbone/base/kustomization.yaml v2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: ../../../helm-base
  releaseName: carbone
  version: 1.0.0
  valuesFile: values.yaml