# argo-cd/roots/root-app-pre.yaml v1.0.0
# Root application for the PRE environment.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-pre
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andres20980/gitops-poc.git
    targetRevision: HEAD
    # This now points specifically to the pre apps directory.
    path: argo-cd/apps/pre
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true