# argo-cd/roots/root-app-pre.yaml
# Root application for the PRE environment using the "App of Apps" pattern
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-pre
  namespace: argocd
spec:
  project: pre-project
  source:
    repoURL: https://github.com/andres20980/gitops-poc.git
    targetRevision: HEAD
    path: argo-cd/apps/pre
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
