# environments/dev/patch-replicas-and-env.yaml v1.0.0
# Patch for DEV: 1 replica and add an environment variable
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: helloworld
          env:
            - name: "ENVIRONMENT"
              value: "development"
